version: "3.9"

services:
  indexnow-worker:
    build: .
    container_name: indexnow-worker
    restart: unless-stopped
    env_file:
      - .env

    # Map host machine into container
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - rss_net

networks:
  rss_net:
    driver: bridge
